INSERT INTO boat VALUES(DEFAULT, 'Harmund', 4, 12);
INSERT INTO boat VALUES(DEFAULT, 'Woden', 10, 30);
INSERT INTO boat VALUES(DEFAULT, 'Hinter', 2, 4);
INSERT INTO boat VALUES(DEFAULT, 'Strom', 4, 5);
INSERT INTO boat VALUES(DEFAULT, 'Hiker', 3, 5);
INSERT INTO boat VALUES(DEFAULT, 'Harsen', 4, 8);
INSERT INTO boat VALUES(DEFAULT, 'Horker', 6, 16);
INSERT INTO boat VALUES(DEFAULT, 'Magnus', 8, 10);
COMMIT;