INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (1, 1, 1921, 'summer', 1329);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (2, 1, 1921, 'autumn', 1483);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (3, 1, 1922, 'summer', 2642);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (4, 1, 1922, 'autumn', 2565);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (5, 1, 1923, 'summer', 2828);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (6, 1, 1923, 'autumn', 3017);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (7, 1, 1924, 'summer', 2534);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (8, 1, 1924, 'autumn', 3353);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (9, 1, 1925, 'summer', 3103);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (10, 1, 1925, 'autumn', 3241);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (11, 1, 1926, 'summer', 4942);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (12, 1, 1926, 'autumn', 4271);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (13, 1, 1927, 'summer', 5245);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (14, 1, 1927, 'autumn', 4995);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (15, 1, 1928, 'summer', 4676);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (16, 1, 1928, 'autumn', 6054);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (17, 1, 1929, 'summer', 5761);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (18, 1, 1929, 'autumn', 6928);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (19, 1, 1930, 'summer', 7994);
INSERT INTO public.harvest (harvest_id, storage_id, harvest_year, harvest_season, food_harvested) VALUES (20, 1, 1930, 'autumn', 7905);
SELECT SETVAL(pg_get_serial_sequence('HARVEST', 'harvest_id'), 21);
COMMIT;