insert into Warrior (person_id) values (1);
insert into Warrior (person_id) values (2);
insert into Warrior (person_id) values (3);
insert into Warrior (person_id) values (4);
insert into Warrior (person_id) values (5);
insert into Warrior (person_id) values (6);
insert into Warrior (person_id) values (7);
insert into Warrior (person_id) values (8);
insert into Warrior (person_id) values (9);
insert into Warrior (person_id) values (10);
insert into Warrior (person_id, favourite_weapon) values (11, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (12, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (13, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (14, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (15, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (16, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (17, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (18, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (19, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (20, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (21, 'Spear');
insert into Warrior (person_id, favourite_weapon) values (22, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (23, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (24, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (25, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (26, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (27, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (28, 'Bow');
insert into Warrior (person_id, favourite_weapon) values (29, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (30, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (31, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (32, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (33, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (34, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (35, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (36, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (37, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (38, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (39, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (40, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (41, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (42, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (43, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (44, 'Sword');
insert into Warrior (person_id, favourite_weapon) values (45, 'Sword');
insert into Warrior values (99, 'Javelin');
insert into Warrior values (100, 'Spear');